# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Synaptics Incorporated

#
# kernel module: pinctrl-myna2.ko
#

MODULE_NAME ?= pinctrl-myna2

EXTRA_CFLAGS += -I$(srctree)/drivers/pinctrl

OBJS := ../berlin.o

obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-objs  = $(OBJS)
