// SPDX-License-Identifier: GPL-2.0
/*
 * Synaptics MYNA2 pinctrl driver
 *
 * Copyright (C) 2023 Synaptics Incorporated
 *
 * Author: Kaicheng xie <Kaicheng.Xie@synaptics.com>
 */

#include <linux/init.h>
#include <linux/of_device.h>
#include <linux/platform_device.h>
#include <linux/regmap.h>
#include <linux/module.h>

#include "berlin.h"

static const struct berlin_desc_group myna2_soc_pinctrl_groups[] = {
	BERLIN_PINCTRLCONF_GROUP("TW0_SCL", 0x0, 0x3, 0x00,
			0x0, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tw0"), /* SCL */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO10 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0a"), /* CTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s4")), /* LRCK */
	BERLIN_PINCTRLCONF_GROUP("TW0_SDA", 0x0, 0x3, 0x03,
			0x4, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tw0"), /* SDA */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO11 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0a"), /* RTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s4")), /* BCLK */
	BERLIN_PINCTRLCONF_GROUP("TW1_SCL", 0x0, 0x3, 0x06,
			0x8, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tw1"), /* SCL */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO12 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s4"), /* DO */
			BERLIN_PINCTRL_FUNCTION(0x5, "io3p3_for_n")),
	BERLIN_PINCTRLCONF_GROUP("TW1_SDA", 0x0, 0x3, 0x09,
			0xc, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tw1"), /* SDA */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO13 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s4"), /* DI */
			BERLIN_PINCTRL_FUNCTION(0x5, "por_vddsoc_rstb")),
	BERLIN_PINCTRLCONF_GROUP("TMS", 0x0, 0x3, 0x0c,
			0x14, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tms"), /* TMS */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO0 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0b"), /* TXD */
			BERLIN_PINCTRL_FUNCTION(0x3, "key")), /* COL2 */
	BERLIN_PINCTRLCONF_GROUP("TDI", 0x0, 0x3, 0x0f,
			0x18, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tdi"), /* TDI */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO1 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0b"), /* RXD */
			BERLIN_PINCTRL_FUNCTION(0x3, "key"), /* COL3 */
			BERLIN_PINCTRL_FUNCTION(0x4, "gpio_trig")), /* GPIO_TRIG[0] */
	BERLIN_PINCTRLCONF_GROUP("TDO", 0x0, 0x3, 0x12,
			0x1c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "tdo"), /* TDO */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO2 */
			BERLIN_PINCTRL_FUNCTION(0x2, "pdmb"), /* CLKIO */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s2")), /* MCLK */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SS0n", 0x0, 0x3, 0x15,
			0x20, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "spi1"), /* SS0n */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio")), /* GPIO3 */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SS1n", 0x0, 0x3, 0x18,
			0x24, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "core_for_n"),
			BERLIN_PINCTRL_FUNCTION(0x1, "spi1"), /* SS1n */
			BERLIN_PINCTRL_FUNCTION(0x2, "gpio"), /* GPIO4 */
			BERLIN_PINCTRL_FUNCTION(0x3, "dsi_te"), /* DSI_TE */
			BERLIN_PINCTRL_FUNCTION(0x4, "gpio_trig")), /* GPIO_TRIG[1] */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SS2n", 0x0, 0x3, 0x1b,
			0x28, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "urt0a"), /* RXD */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi1"), /*  SS2n*/
			BERLIN_PINCTRL_FUNCTION(0x2, "gpio"), /* GPIO5 */
			BERLIN_PINCTRL_FUNCTION(0x4, "gpio_trig")), /* GPIO_TRIG[2] */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SS3n", 0x4, 0x3, 0x00,
			0x2c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "urt0a"), /* TXD */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi1"), /*  SS3n*/
			BERLIN_PINCTRL_FUNCTION(0x2, "gpio")), /* GPIO6 */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SDO", 0x4, 0x3, 0x03,
			0x30, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "spi1"), /* SDO */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO7 */
			BERLIN_PINCTRL_FUNCTION(0x7, "syspll0")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SDI", 0x4, 0x3, 0x06,
			0x34, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "spi1"), /* SDI */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO9 */
			BERLIN_PINCTRL_FUNCTION(0x7, "syspll1")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("SPI1_SCLK", 0x4, 0x3, 0x09,
			0x38, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "spi1"), /* SCLK */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio")), /* GPIO8 */
	BERLIN_PINCTRLCONF_GROUP("TW2_SCL", 0x4, 0x3, 0x0c,
			0x3c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO37 */
			BERLIN_PINCTRL_FUNCTION(0x1, "tw2"), /* SCL */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW0 */
			BERLIN_PINCTRL_FUNCTION(0x3, "rgmiib")), /* MDC */
	BERLIN_PINCTRLCONF_GROUP("TW2_SDA", 0x4, 0x3, 0x0f,
			0x40, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO38 */
			BERLIN_PINCTRL_FUNCTION(0x1, "tw2"), /* SDA */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW1 */
			BERLIN_PINCTRL_FUNCTION(0x3, "rgmiib"), /* MDIO */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG15 */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SS0n", 0x4, 0x3, 0x12,
			0x44, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO30 */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi2")), /* SS0n */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SS1n", 0x4, 0x3, 0x15,
			0x48, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO31 */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi2"), /*  SS1n*/
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* CDC_DIR */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG14 */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SS2n", 0x4, 0x3, 0x18,
			0x4c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "io_por_n"), /* IO_POR_N */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO32 */
			BERLIN_PINCTRL_FUNCTION(0x2, "spi2"), /* SS2n */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* PWR_OK */
			BERLIN_PINCTRL_FUNCTION(0x4, "pdm"), /* DI[2] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG12 */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SS3n", 0x4, 0x3, 0x1b,
			0x50, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "pwr_ok"), /* PWR_OK */
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio"), /* GPIO33 */
			BERLIN_PINCTRL_FUNCTION(0x2, "spi2"), /* SS3n */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* NARES */
			BERLIN_PINCTRL_FUNCTION(0x4, "pdm"), /* DI[3] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG13 */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SDO", 0x8, 0x3, 0x00,
			0x54, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO34 */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi2"), /* SDO */
			BERLIN_PINCTRL_FUNCTION(0x7, "mempll")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SCLK", 0x8, 0x3, 0x03,
			0x58, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO35 */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi2"), /* SCLK */
			BERLIN_PINCTRL_FUNCTION(0x7, "dbg")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("SPI2_SDI", 0x8, 0x3, 0x06,
			0x5c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO36 */
			BERLIN_PINCTRL_FUNCTION(0x1, "spi2"), /* SDI */
			BERLIN_PINCTRL_FUNCTION(0x7, "cpupll")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("TW3_SCL", 0x8, 0x3, 0x09,
			0x60, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO41 */
			BERLIN_PINCTRL_FUNCTION(0x1, "tw3"), /* SCL */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt1a"), /* RTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "if"), /* DCLS */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG7 */
	BERLIN_PINCTRLCONF_GROUP("TW3_SDA", 0x8, 0x3, 0x0c,
			0x64, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO42 */
			BERLIN_PINCTRL_FUNCTION(0x1, "tw3"), /* SDA */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt1a"), /* CTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "if"), /* DCLS_N */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG6 */
	BERLIN_PINCTRLCONF_GROUP("URT1_RXD", 0x8, 0x3, 0x0f,
			0x68, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO39 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt1a"), /* RXD */
			BERLIN_PINCTRL_FUNCTION(0x3, "key"), /* ROW2 */
			BERLIN_PINCTRL_FUNCTION(0x4, "gpio_trig"), /* TRIG[3] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG5 */
	BERLIN_PINCTRLCONF_GROUP("URT1_TXD", 0x8, 0x3, 0x12,
			0x6c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO40 */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt1a"), /* TXD */
			BERLIN_PINCTRL_FUNCTION(0x3, "key"), /* ROW3 */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG4 */
	BERLIN_PINCTRLCONF_GROUP("PWM0", 0x8, 0x3, 0x15,
			0x70, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO46 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pwm"), /* PWM[0] */
			BERLIN_PINCTRL_FUNCTION(0x2, "rgmii"), /* PTP_PPS_O */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG3 */
	BERLIN_PINCTRLCONF_GROUP("PWM1", 0x8, 0x3, 0x18,
			0x74, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO45 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pwm"), /* PWM[1] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG2 */
	BERLIN_PINCTRLCONF_GROUP("PWM2", 0x8, 0x3, 0x1b,
			0x78, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO44 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pwm"), /* PWM[2] */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL1 */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG1 */
	BERLIN_PINCTRLCONF_GROUP("PWM3", 0xc, 0x3, 0x00,
			0x7c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO43 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pwm"), /* PWM[3] */
			BERLIN_PINCTRL_FUNCTION(0x3, "if"), /* DCLS_SCLK */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG0 */
	BERLIN_PINCTRLCONF_GROUP("GPIO_A0", 0xc, 0x3, 0x03,
			0x80, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO50 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmiia"), /* MDIO */
			BERLIN_PINCTRL_FUNCTION(0x2, "pwm"), /* PWM[1] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG8 */
	BERLIN_PINCTRLCONF_GROUP("GPIO_A1", 0xc, 0x3, 0x06,
			0x84, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO49 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmiia"), /* MDC  */
			BERLIN_PINCTRL_FUNCTION(0x2, "pwm"), /* PWM[2] */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG9 */
	BERLIN_PINCTRLCONF_GROUP("GPIO_A2", 0xc, 0x3, 0x09,
			0x88, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO48 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW5 */
			BERLIN_PINCTRL_FUNCTION(0x3, "urt1b"), /* TXD */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG10 */
	BERLIN_PINCTRLCONF_GROUP("GPIO_A3", 0xc, 0x3, 0x0c,
			0x8c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO47 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW4 */
			BERLIN_PINCTRL_FUNCTION(0x3, "urt1b"), /* RXD */
			BERLIN_PINCTRL_FUNCTION(0x7, "phy")), /* DBG11 */
	BERLIN_PINCTRLCONF_GROUP("USB2_DRV_VBUS", 0xc, 0x3, 0x0f,
			0x90, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "usb2_drv_Vbus"),
			BERLIN_PINCTRL_FUNCTION(0x1, "gpio")), /* GPIO51 */
	BERLIN_PINCTRLCONF_GROUP("SDIO_CDn", 0xc, 0x3, 0x12,
			0x94, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO54 */
			BERLIN_PINCTRL_FUNCTION(0x1, "sdio"), /* CDn */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL0 */
			BERLIN_PINCTRL_FUNCTION(0x3, "urt1b")), /* RTSn */
	BERLIN_PINCTRLCONF_GROUP("SDIO_WP", 0xc, 0x3, 0x15,
			0x98, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO55 */
			BERLIN_PINCTRL_FUNCTION(0x1, "sdio"), /* WP */
			BERLIN_PINCTRL_FUNCTION(0x3, "urt1b")), /* CTSn */
	BERLIN_PINCTRLCONF_GROUP("NFALE", 0xc, 0x3, 0x18,
			0x9c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO52 */
			BERLIN_PINCTRL_FUNCTION(0x1, "nfale")), /* NFALE */
	BERLIN_PINCTRLCONF_GROUP("NFLCS", 0xc, 0x3, 0x1b,
			0xa0, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO53 */
			BERLIN_PINCTRL_FUNCTION(0x1, "nflcs")), /* NFLCS */
	BERLIN_PINCTRLCONF_GROUP("RGMII_CLK_OUT", 0x10, 0x3, 0x00,
			0xa4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X53 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* CLK_OUT */
	BERLIN_PINCTRLCONF_GROUP("RGMIITXC", 0x10, 0x3, 0x03,
			0xa8, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X43 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXC */
	BERLIN_PINCTRLCONF_GROUP("RGMIITD0", 0x10, 0x3, 0x06,
			0xac, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X19 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXD[0] */
	BERLIN_PINCTRLCONF_GROUP("RGMIITD1", 0x10, 0x3, 0x09,
			0xb0, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X20 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXD[1] */
	BERLIN_PINCTRLCONF_GROUP("RGMIITD2", 0x10, 0x3, 0x0c,
			0xb4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X21 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXD[2] */
	BERLIN_PINCTRLCONF_GROUP("RGMIITD3", 0x10, 0x3, 0x0f,
			0xb8, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X22 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXD[3] */
	BERLIN_PINCTRLCONF_GROUP("RGMIITXCTL", 0x10, 0x3, 0x12,
			0xbc, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X51 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* TXCTL */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRXC", 0x10, 0x3, 0x15,
			0xc0, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X42 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXC */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRD0", 0x10, 0x3, 0x18,
			0xc4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X31 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXD[0] */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRD1", 0x10, 0x3, 0x1b,
			0xc8, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X32 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXD[1] */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRD2", 0x14, 0x3, 0x00,
			0xcc, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X33 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXD[2] */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRD3", 0x14, 0x3, 0x03,
			0xd0, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X41 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXD[3] */
	BERLIN_PINCTRLCONF_GROUP("RGMIIRXCTL", 0x14, 0x3, 0x06,
			0xd4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X52 */
			BERLIN_PINCTRL_FUNCTION(0x1, "rgmii")), /* RXCTL */
	BERLIN_PINCTRLCONF_GROUP("I2S1_DO", 0x14, 0x3, 0x09,
			0xdc, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO16 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s1"), /* DO */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* CDC_DAT_DA */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[4] */
	BERLIN_PINCTRLCONF_GROUP("I2S1_DI", 0x14, 0x3, 0x0c,
			0xe0, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO18 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s1"), /* DI */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* DAT_DA */
			BERLIN_PINCTRL_FUNCTION(0x4, "apll0"), /* CLKO */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[5] */
	BERLIN_PINCTRLCONF_GROUP("I2S1_LRCK", 0x14, 0x3, 0x0f,
			0xe4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO14 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s1"), /* LRCK */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* CLK_PLL */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[0] */
	BERLIN_PINCTRLCONF_GROUP("I2S1_BCLK", 0x14, 0x3, 0x12,
			0xe8, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO15 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s1"), /* BCLK */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* CDC_DAT_AD */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[1] */
	BERLIN_PINCTRLCONF_GROUP("I2S1_MCLK", 0x14, 0x3, 0x15,
			0xec, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO17 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s1"), /* MCLK */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* CLK_IF */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[3] */
	BERLIN_PINCTRLCONF_GROUP("I2S2_LRCK", 0x14, 0x3, 0x18,
			0xf0, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO19 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s2"), /* LRCK */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0b"), /* CTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if")), /* DAT_AD */
	BERLIN_PINCTRLCONF_GROUP("I2S2_BCLK", 0x14, 0x3, 0x1b,
			0xf4, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO20 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s2"), /* BCLK */
			BERLIN_PINCTRL_FUNCTION(0x2, "urt0b"), /* RTSn */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if")), /* EN_AD */
	BERLIN_PINCTRLCONF_GROUP("I2S2_DO", 0x18, 0x3, 0x00,
			0xf8, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO21 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s2"), /* DO */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* O:EN_DA */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[6] */
	BERLIN_PINCTRLCONF_GROUP("I2S2_DI", 0x18, 0x3, 0x03,
			0xfc, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO22 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s2"), /* DI */
			BERLIN_PINCTRL_FUNCTION(0x3, "daif_if"), /* INT_ANA */
			BERLIN_PINCTRL_FUNCTION(0x4, "vpll0"), /* CLKO */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[7] */
	BERLIN_PINCTRLCONF_GROUP("PDM_CLKIO", 0x18, 0x3, 0x06,
			0x100, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO25 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pdm"), /* CLKIO */
			BERLIN_PINCTRL_FUNCTION(0x2, "i2s2")), /* MCLK */
	BERLIN_PINCTRLCONF_GROUP("PDM_DI0", 0x18, 0x3, 0x09,
			0x104, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO24 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pdm")), /* DI[0] */
	BERLIN_PINCTRLCONF_GROUP("PDM_DI1", 0x18, 0x3, 0x0c,
			0x108, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO23 */
			BERLIN_PINCTRL_FUNCTION(0x1, "pdm")), /* DI[1] */
	BERLIN_PINCTRLCONF_GROUP("I2S3_DO", 0x18, 0x3, 0x0f,
			0x10c, 0x3, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO28 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s3"), /* DO */
			BERLIN_PINCTRL_FUNCTION(0x4, "apll1"), /* CLKO */
			BERLIN_PINCTRL_FUNCTION(0x7, "aio")), /* DBG[2] */
	BERLIN_PINCTRLCONF_GROUP("I2S3_LRCK", 0x18, 0x3, 0x12,
			0x110, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO26 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s3")), /* LRCK */
	BERLIN_PINCTRLCONF_GROUP("I2S3_BCLK", 0x18, 0x3, 0x15,
			0x114, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO27 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s3")), /* BCLK*/
	BERLIN_PINCTRLCONF_GROUP("I2S3_DI", 0x18, 0x3, 0x18,
			0x118, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO29 */
			BERLIN_PINCTRL_FUNCTION(0x1, "i2s3"), /* DI */
			BERLIN_PINCTRL_FUNCTION(0x4, "vpll1")), /* CLKO */
	BERLIN_PINCTRLCONF_GROUP("LCDD0", 0x18, 0x3, 0x1b,
			0x11c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X12 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD0 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW6 */
			BERLIN_PINCTRL_FUNCTION(0x3, "tw3b")), /* SCL */
	BERLIN_PINCTRLCONF_GROUP("LCDD1", 0x1c, 0x3, 0x00,
			0x120, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X13 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD1 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW7 */
			BERLIN_PINCTRL_FUNCTION(0x3, "tw3b")), /* SDA */
	BERLIN_PINCTRLCONF_GROUP("LCDD2", 0x1c, 0x3, 0x03,
			0x124, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO56 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD2 */
	BERLIN_PINCTRLCONF_GROUP("LCDD3", 0x1c, 0x3, 0x06,
			0x128, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO57 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD3 */
	BERLIN_PINCTRLCONF_GROUP("LCDD4", 0x1c, 0x3, 0x09,
			0x12c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO58 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD4 */
	BERLIN_PINCTRLCONF_GROUP("LCDD5", 0x1c, 0x3, 0x0c,
			0x130, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO59 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD5 */
	BERLIN_PINCTRLCONF_GROUP("LCDD6", 0x1c, 0x3, 0x0f,
			0x134, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO60 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD6 */
	BERLIN_PINCTRLCONF_GROUP("LCDD7", 0x1c, 0x3, 0x12,
			0x138, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO61 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD7 */
	BERLIN_PINCTRLCONF_GROUP("LCDD8", 0x1c, 0x3, 0x15,
			0x13c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X0 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD8 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL6 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s5")), /* DO */
	BERLIN_PINCTRLCONF_GROUP("LCDD9", 0x1c, 0x3, 0x18,
			0x140, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X1 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD9 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL7 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s5")), /* DI */
	BERLIN_PINCTRLCONF_GROUP("LCDD10", 0x1c, 0x3, 0x1b,
			0x144, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO62 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD10 */
	BERLIN_PINCTRLCONF_GROUP("LCDD11", 0x20, 0x3, 0x00,
			0x148, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO63 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD11 */
	BERLIN_PINCTRLCONF_GROUP("LCDD12", 0x20, 0x3, 0x03,
			0x14c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO64 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD12 */
	BERLIN_PINCTRLCONF_GROUP("LCDD13", 0x20, 0x3, 0x06,
			0x150, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO65 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD13 */
	BERLIN_PINCTRLCONF_GROUP("LCDD14", 0x20, 0x3, 0x09,
			0x154, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO66 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD14 */
	BERLIN_PINCTRLCONF_GROUP("LCDD15", 0x20, 0x3, 0x0c,
			0x158, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO67 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD15 */
	BERLIN_PINCTRLCONF_GROUP("LCDD16", 0x20, 0x3, 0x0f,
			0x15c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X2 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD16 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW8 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s5")), /* LRCK */
	BERLIN_PINCTRLCONF_GROUP("LCDD17", 0x20, 0x3, 0x12,
			0x160, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X39 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd"), /* LCDD17 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* ROW9 */
			BERLIN_PINCTRL_FUNCTION(0x3, "i2s5")), /* BCLK */
	BERLIN_PINCTRLCONF_GROUP("LCDD18", 0x20, 0x3, 0x15,
			0x164, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO68 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD18 */
	BERLIN_PINCTRLCONF_GROUP("LCDD19", 0x20, 0x3, 0x18,
			0x168, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO69 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD19 */
	BERLIN_PINCTRLCONF_GROUP("LCDD20", 0x20, 0x3, 0x1b,
			0x16c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO70 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD20 */
	BERLIN_PINCTRLCONF_GROUP("LCDD21", 0x24, 0x3, 0x00,
			0x170, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO71 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD21 */
	BERLIN_PINCTRLCONF_GROUP("LCDD22", 0x24, 0x3, 0x03,
			0x174, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X40 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD22 */
	BERLIN_PINCTRLCONF_GROUP("LCDD23", 0x24, 0x3, 0x06,
			0x178, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X14 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcd")), /* LCDD23 */
	BERLIN_PINCTRLCONF_GROUP("LPCLK", 0x24, 0x3, 0x09,
			0x17c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X15 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lpclk")), /* LPCLK */
	BERLIN_PINCTRLCONF_GROUP("LCDGPIO0", 0x24, 0x3, 0x0c,
			0x180, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X16 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcdgpio")), /* LCDGPIO0 */
	BERLIN_PINCTRLCONF_GROUP("LCDGPIO1", 0x24, 0x3, 0x0f,
			0x184, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X17 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcdgpio")), /* LCDGPIO1 */
	BERLIN_PINCTRLCONF_GROUP("LCDGPIO2", 0x24, 0x3, 0x12,
			0x188, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X18 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcdgpio")), /* LCDGPIO2 */
	BERLIN_PINCTRLCONF_GROUP("LCDGPIO3", 0x24, 0x3, 0x15,
			0x18c, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X10 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcdgpio"), /* LCDGPIO3 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL4 */
			BERLIN_PINCTRL_FUNCTION(0x3, "sdio")), /* SDIOB_CDn */
	BERLIN_PINCTRLCONF_GROUP("LCDGPIO4", 0x24, 0x3, 0x18,
			0x190, 0x4, 0x0,
			BERLIN_PINCTRL_FUNCTION(0x0, "gpio"), /* GPIO_X11 */
			BERLIN_PINCTRL_FUNCTION(0x1, "lcdgpio"), /* LCDGPIO4 */
			BERLIN_PINCTRL_FUNCTION(0x2, "key"), /* COL5 */
			BERLIN_PINCTRL_FUNCTION(0x3, "sdio")), /* SDIOB_WP */
};

static const struct berlin_pinctrl_desc myna2_soc_pinctrl_data = {
	.groups = myna2_soc_pinctrl_groups,
	.ngroups = ARRAY_SIZE(myna2_soc_pinctrl_groups),
};

static const struct of_device_id myna2_pinctrl_match[] = {
	{
		.compatible = "syna,myna2-soc-pinctrl",
		.data = &myna2_soc_pinctrl_data,
	},
	{}
};

static int myna2_pinctrl_probe(struct platform_device *pdev)
{
	const struct of_device_id *match =
		of_match_device(myna2_pinctrl_match, &pdev->dev);
	struct regmap_config *rmconfig;
	struct regmap *regmap, *conf;
	struct resource *res;
	void __iomem *base;

	rmconfig = devm_kzalloc(&pdev->dev, sizeof(*rmconfig), GFP_KERNEL);
	if (!rmconfig)
		return -ENOMEM;

	res = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	base = devm_ioremap_resource(&pdev->dev, res);
	if (IS_ERR(base))
		return PTR_ERR(base);

	rmconfig->reg_bits = 32,
	rmconfig->val_bits = 32,
	rmconfig->reg_stride = 4,
	rmconfig->max_register = resource_size(res);

	regmap = devm_regmap_init_mmio(&pdev->dev, base, rmconfig);
	if (IS_ERR(regmap))
		return PTR_ERR(regmap);

	res = platform_get_resource(pdev, IORESOURCE_MEM, 1);
	base = devm_ioremap_resource(&pdev->dev, res);
	if (IS_ERR(base))
		return PTR_ERR(base);

	rmconfig->name = "conf";
	rmconfig->max_register = resource_size(res);

	conf = devm_regmap_init_mmio(&pdev->dev, base, rmconfig);
	if (IS_ERR(conf))
		return PTR_ERR(conf);

	return berlin_pinctrl_probe_regmap(pdev, match->data, regmap, conf);
}

static struct platform_driver myna2_pinctrl_driver = {
	.probe	= myna2_pinctrl_probe,
	.driver	= {
		.name = "myna2-pinctrl",
		.of_match_table = myna2_pinctrl_match,
	},
};

static int __init myna2_pinctrl_init(void)
{
	return platform_driver_register(&myna2_pinctrl_driver);
}
arch_initcall(myna2_pinctrl_init);

MODULE_LICENSE("GPL v2");
