# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Synaptics Incorporated

#
# kernel module: dolphin-pll.ko
#

MODULE_NAME ?= dolphin-pll

EXTRA_CFLAGS += -I$(src)/..

OBJS := ../clk.o \
		../gate.o

obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-objs  = $(OBJS)
