# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Synaptics Incorporated

#
# kernel module: dolphin-pll.ko
#

MODULE_NAME ?= dolphin-pll

obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-objs  = $(OBJS)
