# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Synaptics Incorporated

#
# kernel module: dolphin-clks.ko
#

MODULE_NAME ?= dolphin-clks

EXTRA_CFLAGS += -I$(src)/..

OBJS := ../clk.o \
		../gate.o

obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-objs  = $(OBJS)
